export interface SeedTask {
  title: string;
  description?: string;
  priority: number;
  due: number | null;
  assignee: string;
  done?: boolean;
  completed?: number;
}

export interface SeedProject {
  name: string;
  color: string;
  tasks: SeedTask[];
}

export interface SeedComment {
  project: string;
  task: number;
  author: string;
  daysAgo: number;
  body: string;
}

export interface SeedOrg {
  slug: string;
  name: string;
  plan: string;
  users: { key: string; email: string; name: string; role: string; timezone: string }[];
  projects: SeedProject[];
  comments: SeedComment[];
  invoices: { monthsAgo: number; amount_cents: number; status: string }[];
}

export const PASSWORD = 'demo-pass-2026';

export const ORGS: SeedOrg[] = [
  {
    slug: 'brightloom',
    name: 'Brightloom',
    plan: 'team',
    users: [
      {
        key: 'priya',
        email: 'priya@brightloom.test',
        name: 'Priya Raman',
        role: 'owner',
        timezone: 'Europe/London',
      },
      {
        key: 'marcus',
        email: 'marcus@brightloom.test',
        name: 'Marcus Bell',
        role: 'member',
        timezone: 'Europe/London',
      },
      {
        key: 'aisha',
        email: 'aisha@brightloom.test',
        name: 'Aisha Khan',
        role: 'member',
        timezone: 'Asia/Kolkata',
      },
    ],
    projects: [
      {
        name: 'Website relaunch',
        color: 'blue',
        tasks: [
          {
            title: 'Audit the current site content inventory',
            description: 'One row per page, with the owner and whether it survives the move.',
            priority: 3,
            due: -22,
            assignee: 'aisha',
            done: true,
            completed: -22,
          },
          {
            title: 'Agree the sitemap for the new site',
            priority: 3,
            due: -18,
            assignee: 'priya',
            done: true,
            completed: -17,
          },
          {
            title: 'Write the new pricing page copy',
            description: 'Three plans, no comparison table. Keep it under 200 words.',
            priority: 3,
            due: -12,
            assignee: 'priya',
            done: true,
            completed: -12,
          },
          {
            title: 'Book the photographer for the team page',
            priority: 3,
            due: -8,
            assignee: 'aisha',
            done: true,
            completed: -8,
          },
          {
            title: 'Set up staging deploys for the new site',
            priority: 3,
            due: -6,
            assignee: 'marcus',
            done: true,
            completed: -6,
          },
          {
            title: 'Rebuild the navigation component',
            description:
              'The current one breaks below 380px and the submenu traps keyboard focus.',
            priority: 2,
            due: -4,
            assignee: 'marcus',
          },
          {
            title: 'Fix the contact form validation',
            description: 'An empty message field still submits and the reply never arrives.',
            priority: 1,
            due: -2,
            assignee: 'marcus',
          },
          {
            title: 'Compress the hero images',
            priority: 3,
            due: 0,
            assignee: 'aisha',
          },
          {
            title: 'Review the design tokens with Marcus',
            priority: 3,
            due: 0,
            assignee: 'priya',
          },
          {
            title: 'Set up redirects for the retired URLs',
            priority: 3,
            due: 0,
            assignee: 'marcus',
            done: true,
            completed: 0,
          },
          {
            title: 'Move the blog posts to the new CMS',
            description: 'Forty two posts. Keep the published dates and the author bylines.',
            priority: 3,
            due: 1,
            assignee: 'aisha',
          },
          {
            title: 'Get legal sign-off on the terms page',
            priority: 2,
            due: 3,
            assignee: 'priya',
          },
          {
            title: 'Add analytics to the signup flow',
            priority: 3,
            due: 5,
            assignee: 'marcus',
          },
          {
            title: 'Draft the launch announcement',
            priority: 3,
            due: 8,
            assignee: 'priya',
          },
          {
            title: 'Test the site on Safari 16',
            priority: 3,
            due: 11,
            assignee: 'aisha',
          },
          {
            title: 'Remove the old marketing scripts',
            priority: 3,
            due: 13,
            assignee: 'marcus',
          },
          {
            title: 'Check the print stylesheet still works',
            priority: 4,
            due: 14,
            assignee: 'aisha',
          },
          {
            title: 'Replace the stock photography on the homepage',
            priority: 4,
            due: null,
            assignee: 'aisha',
          },
        ],
      },
      {
        name: 'Mobile app',
        color: 'amber',
        tasks: [
          {
            title: 'Replace the deprecated camera permission call',
            priority: 3,
            due: -19,
            assignee: 'marcus',
            done: true,
            completed: -19,
          },
          {
            title: 'Move the API base URL into the build config',
            priority: 3,
            due: -14,
            assignee: 'marcus',
            done: true,
            completed: -14,
          },
          {
            title: 'Add a crash reporter to the beta build',
            priority: 3,
            due: -9,
            assignee: 'aisha',
            done: true,
            completed: -9,
          },
          {
            title: 'Fix the crash on cold start on Android 13',
            description: 'Only on devices with the app installed from the beta channel.',
            priority: 1,
            due: -6,
            assignee: 'marcus',
          },
          {
            title: 'Trim the splash screen delay',
            priority: 3,
            due: -5,
            assignee: 'aisha',
            done: true,
            completed: -4,
          },
          {
            title: 'Investigate battery use during background sync',
            priority: 3,
            due: -3,
            assignee: 'aisha',
          },
          {
            title: 'Reduce the app bundle below 30 MB',
            priority: 2,
            due: -1,
            assignee: 'marcus',
          },
          {
            title: 'Add offline caching for the task list',
            description: 'Read only is fine for 2.4. Writes can wait for 2.5.',
            priority: 2,
            due: 0,
            assignee: 'marcus',
          },
          {
            title: 'Handle expired sessions without a logout loop',
            priority: 2,
            due: 0,
            assignee: 'aisha',
            done: true,
            completed: 0,
          },
          {
            title: 'Write the release notes for 2.4',
            priority: 3,
            due: 2,
            assignee: 'priya',
          },
          {
            title: 'Ship push notifications for tasks due today',
            priority: 3,
            due: 4,
            assignee: 'marcus',
          },
          {
            title: 'Update the onboarding screens',
            priority: 3,
            due: 6,
            assignee: 'aisha',
          },
          {
            title: 'Add a dark theme to the settings screen',
            priority: 4,
            due: 9,
            assignee: 'aisha',
          },
          {
            title: 'Fix the keyboard covering the comment box',
            priority: 3,
            due: 12,
            assignee: 'marcus',
          },
          {
            title: 'Submit 2.4 to the App Store',
            priority: 1,
            due: 14,
            assignee: 'priya',
          },
          {
            title: 'Retire the old settings deep link',
            priority: 4,
            due: null,
            assignee: 'marcus',
          },
        ],
      },
      {
        name: 'Q4 planning',
        color: 'violet',
        tasks: [
          {
            title: 'Draft the Q4 goals document',
            priority: 2,
            due: -16,
            assignee: 'priya',
            done: true,
            completed: -15,
          },
          {
            title: 'Summarise the Q3 results',
            priority: 3,
            due: -11,
            assignee: 'priya',
            done: true,
            completed: -11,
          },
          {
            title: 'Confirm the travel budget with finance',
            priority: 3,
            due: -7,
            assignee: 'aisha',
            done: true,
            completed: -7,
          },
          {
            title: 'Write the Q4 hiring forecast',
            priority: 2,
            due: -5,
            assignee: 'priya',
          },
          {
            title: 'Pick the metrics we report weekly',
            priority: 3,
            due: -3,
            assignee: 'marcus',
            done: true,
            completed: -3,
          },
          {
            title: 'Collect headcount requests from each team',
            priority: 2,
            due: -2,
            assignee: 'priya',
          },
          {
            title: 'Book the offsite venue',
            description: 'Two days in the second week of November, room for sixteen.',
            priority: 3,
            due: 0,
            assignee: 'aisha',
          },
          {
            title: 'Review the marketing budget with Aisha',
            priority: 3,
            due: 0,
            assignee: 'priya',
          },
          {
            title: 'Schedule the Q4 kickoff call',
            priority: 3,
            due: 2,
            assignee: 'aisha',
          },
          {
            title: 'Set the pricing experiment schedule',
            priority: 3,
            due: 3,
            assignee: 'priya',
          },
          {
            title: 'Agree the support cover for the holidays',
            priority: 3,
            due: 7,
            assignee: 'marcus',
          },
          {
            title: 'Update the roadmap slides',
            priority: 3,
            due: 10,
            assignee: 'priya',
          },
          {
            title: 'Share the plan with the board',
            priority: 2,
            due: 13,
            assignee: 'priya',
          },
        ],
      },
      {
        name: 'Hiring',
        color: 'green',
        tasks: [
          {
            title: 'Write the job description for a backend engineer',
            priority: 3,
            due: -20,
            assignee: 'priya',
            done: true,
            completed: -20,
          },
          {
            title: 'Post the design role on the job board',
            priority: 3,
            due: -13,
            assignee: 'aisha',
            done: true,
            completed: -13,
          },
          {
            title: 'Collect feedback from the last two panels',
            priority: 3,
            due: -6,
            assignee: 'marcus',
            done: true,
            completed: -6,
          },
          {
            title: 'Reply to the recruiting agency',
            priority: 3,
            due: -4,
            assignee: 'priya',
          },
          {
            title: 'Ask the team for referrals',
            priority: 4,
            due: -2,
            assignee: 'aisha',
            done: true,
            completed: -2,
          },
          {
            title: 'Review the take-home exercise',
            description: 'Two submissions waiting since Friday.',
            priority: 1,
            due: -1,
            assignee: 'marcus',
          },
          {
            title: 'Schedule the interviews for the design role',
            priority: 2,
            due: 0,
            assignee: 'aisha',
          },
          {
            title: 'Send the offer to the senior designer',
            priority: 2,
            due: 1,
            assignee: 'priya',
          },
          {
            title: 'Book a room for the panel on Thursday',
            priority: 3,
            due: 2,
            assignee: 'aisha',
          },
          {
            title: 'Update the interview scorecard',
            priority: 3,
            due: 4,
            assignee: 'marcus',
          },
          {
            title: 'Check the visa timeline for the Berlin candidate',
            priority: 3,
            due: 6,
            assignee: 'priya',
          },
          {
            title: 'Add the new hire to payroll',
            priority: 3,
            due: 8,
            assignee: 'priya',
          },
          {
            title: 'Prepare the first week plan for the new engineer',
            priority: 3,
            due: 11,
            assignee: 'marcus',
          },
          {
            title: 'Refresh the careers page copy',
            priority: 4,
            due: 14,
            assignee: 'aisha',
          },
        ],
      },
    ],
    comments: [
      {
        project: 'Website relaunch',
        task: 5,
        author: 'priya',
        daysAgo: 6,
        body: 'The submenu is the part I care about. Keyboard focus has to come back to the trigger.',
      },
      {
        project: 'Website relaunch',
        task: 5,
        author: 'marcus',
        daysAgo: 5,
        body: 'Rewriting it with a plain details element. Half the code and it behaves.',
      },
      {
        project: 'Website relaunch',
        task: 5,
        author: 'priya',
        daysAgo: 3,
        body: 'Good. Ping me when it is on staging and I will click through it.',
      },
      {
        project: 'Website relaunch',
        task: 6,
        author: 'aisha',
        daysAgo: 4,
        body: 'Reproduced. The submit handler never checks the message field, only the email.',
      },
      {
        project: 'Website relaunch',
        task: 6,
        author: 'marcus',
        daysAgo: 2,
        body: 'Fix is small. I want a test around it before it goes out.',
      },
      {
        project: 'Website relaunch',
        task: 8,
        author: 'priya',
        daysAgo: 2,
        body: 'Let us settle the spacing scale first, the rest follows from it.',
      },
      {
        project: 'Website relaunch',
        task: 10,
        author: 'aisha',
        daysAgo: 7,
        body: 'The export from the old CMS keeps the dates. The bylines need a manual pass.',
      },
      {
        project: 'Website relaunch',
        task: 10,
        author: 'priya',
        daysAgo: 5,
        body: 'A manual pass on forty two posts is fine. Split it with me.',
      },
      {
        project: 'Website relaunch',
        task: 11,
        author: 'priya',
        daysAgo: 1,
        body: 'Sent the draft to legal on Tuesday. Nothing back yet.',
      },
      {
        project: 'Website relaunch',
        task: 13,
        author: 'marcus',
        daysAgo: 3,
        body: 'Announcement should wait until the redirects are live, otherwise the links break.',
      },
      {
        project: 'Website relaunch',
        task: 2,
        author: 'priya',
        daysAgo: 12,
        body: 'Copy is done. Moved the FAQ to its own page, it was making the layout heavy.',
      },
      {
        project: 'Mobile app',
        task: 3,
        author: 'marcus',
        daysAgo: 5,
        body: 'Only reproduces on the beta channel build, which points at the old auth host.',
      },
      {
        project: 'Mobile app',
        task: 3,
        author: 'aisha',
        daysAgo: 4,
        body: 'The crash reporter now has three stacks from it, all in the session restore path.',
      },
      {
        project: 'Mobile app',
        task: 3,
        author: 'marcus',
        daysAgo: 1,
        body: 'Found it. We read the token before the keystore is unlocked.',
      },
      {
        project: 'Mobile app',
        task: 5,
        author: 'aisha',
        daysAgo: 3,
        body: 'Sync wakes the radio every ninety seconds. That is the whole battery story.',
      },
      {
        project: 'Mobile app',
        task: 6,
        author: 'marcus',
        daysAgo: 2,
        body: 'Down to 31.4 MB after dropping the two unused icon sets.',
      },
      {
        project: 'Mobile app',
        task: 7,
        author: 'marcus',
        daysAgo: 2,
        body: 'Read only cache for 2.4. Writes need conflict handling and that is not a day of work.',
      },
      {
        project: 'Mobile app',
        task: 9,
        author: 'priya',
        daysAgo: 1,
        body: 'Notes should mention the offline list. It is the only thing people asked for.',
      },
      {
        project: 'Mobile app',
        task: 10,
        author: 'aisha',
        daysAgo: 4,
        body: 'The notification copy needs to be short. Two lines at most on Android.',
      },
      {
        project: 'Mobile app',
        task: 14,
        author: 'priya',
        daysAgo: 2,
        body: 'Review takes two days at the moment, so we need the build in on Monday.',
      },
      {
        project: 'Q4 planning',
        task: 3,
        author: 'priya',
        daysAgo: 4,
        body: 'Two backend, one designer. I will hold the second backend role until January.',
      },
      {
        project: 'Q4 planning',
        task: 5,
        author: 'marcus',
        daysAgo: 3,
        body: 'Four teams in, two to go. Marketing has not replied since last Thursday.',
      },
      {
        project: 'Q4 planning',
        task: 6,
        author: 'aisha',
        daysAgo: 2,
        body: 'Two venues can take us. One has no wifi in the side room, which rules it out.',
      },
      {
        project: 'Q4 planning',
        task: 6,
        author: 'priya',
        daysAgo: 1,
        body: 'Book the other one then. Confirm the numbers before Friday.',
      },
      {
        project: 'Q4 planning',
        task: 7,
        author: 'priya',
        daysAgo: 1,
        body: 'Bring the channel split. Last quarter we spent most of it on one experiment.',
      },
      {
        project: 'Q4 planning',
        task: 9,
        author: 'priya',
        daysAgo: 3,
        body: 'Two experiments a month is the most we can read properly.',
      },
      {
        project: 'Q4 planning',
        task: 11,
        author: 'marcus',
        daysAgo: 2,
        body: 'Roadmap slides need the mobile dates from Marcus before they mean anything.',
      },
      {
        project: 'Q4 planning',
        task: 12,
        author: 'priya',
        daysAgo: 1,
        body: 'Board wants one page, not twenty. I will cut it down once the numbers are in.',
      },
      {
        project: 'Hiring',
        task: 3,
        author: 'priya',
        daysAgo: 5,
        body: 'They sent four profiles. Two are worth a call, the rest are not close.',
      },
      {
        project: 'Hiring',
        task: 5,
        author: 'marcus',
        daysAgo: 3,
        body: 'First one is strong on tests and light on the data model question.',
      },
      {
        project: 'Hiring',
        task: 5,
        author: 'aisha',
        daysAgo: 2,
        body: 'Second submission never handles an empty list. Worth asking about in the call.',
      },
      {
        project: 'Hiring',
        task: 6,
        author: 'aisha',
        daysAgo: 1,
        body: 'Three of the four panel slots are confirmed. Waiting on Marcus for Thursday.',
      },
      {
        project: 'Hiring',
        task: 7,
        author: 'priya',
        daysAgo: 1,
        body: 'Offer is approved. I will send it once the panel notes are written up.',
      },
      {
        project: 'Hiring',
        task: 9,
        author: 'marcus',
        daysAgo: 4,
        body: 'The scorecard has nine questions and nobody fills in more than four.',
      },
      {
        project: 'Hiring',
        task: 10,
        author: 'priya',
        daysAgo: 2,
        body: 'Visa timeline is eight to twelve weeks, so a January start at the earliest.',
      },
      {
        project: 'Hiring',
        task: 12,
        author: 'marcus',
        daysAgo: 1,
        body: 'First week should be one small change shipped to production. Nothing bigger.',
      },
      {
        project: 'Hiring',
        task: 1,
        author: 'aisha',
        daysAgo: 13,
        body: 'Posted on two boards. The third one wanted a salary range we have not agreed.',
      },
      {
        project: 'Hiring',
        task: 0,
        author: 'priya',
        daysAgo: 20,
        body: 'Kept it to six bullets. Long descriptions put people off applying.',
      },
      {
        project: 'Mobile app',
        task: 1,
        author: 'marcus',
        daysAgo: 14,
        body: 'Config now reads from the build flavour, so the beta build stops pointing at prod.',
      },
      {
        project: 'Website relaunch',
        task: 4,
        author: 'marcus',
        daysAgo: 6,
        body: 'Staging deploys on every push to the branch. Takes about ninety seconds.',
      },
    ],
    invoices: [
      { monthsAgo: 3, amount_cents: 4800, status: 'paid' },
      { monthsAgo: 2, amount_cents: 4800, status: 'paid' },
      { monthsAgo: 1, amount_cents: 4800, status: 'open' },
    ],
  },
  {
    slug: 'northwind',
    name: 'Northwind Labs',
    plan: 'starter',
    users: [
      {
        key: 'dana',
        email: 'dana@northwind.test',
        name: 'Dana Whitfield',
        role: 'owner',
        timezone: 'America/New_York',
      },
      {
        key: 'lee',
        email: 'lee@northwind.test',
        name: 'Lee Nakamura',
        role: 'member',
        timezone: 'America/New_York',
      },
    ],
    projects: [
      {
        name: 'Warehouse dashboard',
        color: 'blue',
        tasks: [
          {
            title: 'Archive the pilot warehouse data',
            priority: 3,
            due: -12,
            assignee: 'lee',
            done: true,
            completed: -12,
          },
          {
            title: 'Add a filter for out of stock items',
            priority: 3,
            due: -9,
            assignee: 'dana',
            done: true,
            completed: -9,
          },
          {
            title: 'Rename the dashboard tabs',
            priority: 4,
            due: -5,
            assignee: 'lee',
            done: true,
            completed: -5,
          },
          {
            title: 'Add stock alerts to the overview',
            priority: 3,
            due: -3,
            assignee: 'dana',
          },
          {
            title: 'Fix the timezone on the shift summary',
            priority: 3,
            due: -2,
            assignee: 'lee',
            done: true,
            completed: -2,
          },
          {
            title: 'Correct the units on the volume chart',
            priority: 2,
            due: -1,
            assignee: 'lee',
          },
          {
            title: 'Fix the totals on the weekly export',
            priority: 2,
            due: 0,
            assignee: 'dana',
          },
          {
            title: 'Move the dashboard to the shared account',
            priority: 3,
            due: 1,
            assignee: 'lee',
          },
          {
            title: 'Speed up the inventory query',
            priority: 3,
            due: 2,
            assignee: 'lee',
          },
          {
            title: 'Write the handover notes for the night shift',
            priority: 3,
            due: 5,
            assignee: 'dana',
          },
          {
            title: 'Replace the CSV export with a background job',
            priority: 3,
            due: 8,
            assignee: 'lee',
          },
          {
            title: 'Check the report totals against the ledger',
            priority: 3,
            due: 11,
            assignee: 'dana',
          },
          {
            title: 'Add a print layout for the daily sheet',
            priority: 4,
            due: 13,
            assignee: 'dana',
          },
        ],
      },
      {
        name: 'Supplier portal',
        color: 'rose',
        tasks: [
          {
            title: 'Add a status badge to the supplier table',
            priority: 3,
            due: -10,
            assignee: 'dana',
            done: true,
            completed: -10,
          },
          {
            title: 'Add a note field to the supplier record',
            priority: 3,
            due: -7,
            assignee: 'lee',
            done: true,
            completed: -7,
          },
          {
            title: 'Review the portal access list',
            priority: 2,
            due: -4,
            assignee: 'dana',
          },
          {
            title: 'Fix the broken invoice download',
            priority: 1,
            due: -2,
            assignee: 'lee',
          },
          {
            title: 'Remove the test suppliers from the list',
            priority: 4,
            due: -1,
            assignee: 'lee',
            done: true,
            completed: -1,
          },
          {
            title: 'Send the supplier onboarding email',
            priority: 3,
            due: 0,
            assignee: 'dana',
          },
          {
            title: 'Add a contact list to each supplier page',
            priority: 3,
            due: 3,
            assignee: 'lee',
          },
          {
            title: 'Chase the two unsigned contracts',
            priority: 2,
            due: 4,
            assignee: 'dana',
          },
          {
            title: 'Collect the missing tax numbers',
            priority: 3,
            due: 6,
            assignee: 'dana',
          },
          {
            title: 'Retire the old supplier import',
            priority: 3,
            due: 9,
            assignee: 'lee',
          },
          {
            title: 'Write the supplier support guide',
            priority: 3,
            due: 12,
            assignee: 'dana',
          },
          {
            title: 'Confirm the payment terms with Lee',
            priority: 3,
            due: 14,
            assignee: 'dana',
          },
        ],
      },
    ],
    comments: [
      {
        project: 'Warehouse dashboard',
        task: 6,
        author: 'dana',
        daysAgo: 2,
        body: 'The weekly total is off by one shift. It drops the Sunday night rows.',
      },
      {
        project: 'Warehouse dashboard',
        task: 6,
        author: 'lee',
        daysAgo: 1,
        body: 'The week boundary is computed in UTC and the site runs on local time.',
      },
      {
        project: 'Warehouse dashboard',
        task: 3,
        author: 'lee',
        daysAgo: 3,
        body: 'Alerts should fire once a day, not on every refresh.',
      },
      {
        project: 'Supplier portal',
        task: 3,
        author: 'dana',
        daysAgo: 2,
        body: 'The download returns an empty file for anything before June.',
      },
      {
        project: 'Supplier portal',
        task: 2,
        author: 'dana',
        daysAgo: 4,
        body: 'Four accounts belong to people who left. Removing them this week.',
      },
      {
        project: 'Supplier portal',
        task: 5,
        author: 'lee',
        daysAgo: 1,
        body: 'Draft is ready. It needs the new support address before it goes out.',
      },
    ],
    invoices: [{ monthsAgo: 1, amount_cents: 1800, status: 'paid' }],
  },
];
